// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQ_Pjj5FBFZAiFDNpZInSSc91tiw_kTw',
    appId: '1:1024842670611:web:a2de220ca3f694680b55e6',
    messagingSenderId: '1024842670611',
    projectId: 'chat-app-b3422',
    authDomain: 'chat-app-b3422.firebaseapp.com',
    storageBucket: 'chat-app-b3422.appspot.com',
    measurementId: 'G-GV71TCFTZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydgdQlazbf3eegzpfUDxlem_8_zt4Fa8',
    appId: '1:1024842670611:android:4f20da58ab21fa4d0b55e6',
    messagingSenderId: '1024842670611',
    projectId: 'chat-app-b3422',
    storageBucket: 'chat-app-b3422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUHNxLyM2E-rL8hna4ro9QIxUC7RZYZcs',
    appId: '1:1024842670611:ios:8823b5a81450482f0b55e6',
    messagingSenderId: '1024842670611',
    projectId: 'chat-app-b3422',
    storageBucket: 'chat-app-b3422.appspot.com',
    iosBundleId: 'com.example.proto',
  );
}
